name: Static Analysis

on:
  - push
  - pull_request

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --prefer-dist"

jobs:
  tests:
    name: "PHPStan"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.2"

    steps:
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install latest dependencies"
        run: "composer update ${{ env.COMPOSER_FLAGS }}"

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse
